name: Nox
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - uses: excitedleigh/setup-nox@v2.0.0
    - run: nox
